name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Install-require
      run: sudo apt-get install cmake clang-tidy clang-format valgrind lcov

    - name: Build
      working-directory: ${{github.workspace}}
      run: make build

    - name: Lint
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: make lint 

    - name: Test
      working-directory: ${{github.workspace}}
      run: make test

    - name: Run
      working-directory: ${{github.workspace}}
      run: ./build/MatrixCalculator

    - name: Memleaks
      working-directory: ${{github.workspace}}
      run: make memleak

    - name: Run coverage analyse
      working-directory: ${{github.workspace}}/build/tests
      run: |
          lcov -t "MatrixCalculator" -o coverage.info -c -d ./CMakeFiles/MatrixCalculator_unittest.dir
          lcov --remove coverage.info -o coverage.info '/usr/include/*' 

    - name: Get coverage page
      working-directory: ${{github.workspace}}/build/tests
      run: |
          genhtml -o report coverage.info

    - name: Load coverage result
      uses: actions/upload-artifact@v3
      with:
        name: Coverage
        path: build/tests/report/*
