name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Install-require
      run: apt-get install cmake clang-tidy clang-format valgrind
    - name: Lint
      run: make lint 
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Run
      run: ./build/
    - name: Memleaks
      run: make memleak
